---
driver:
  name: docker
  image: ubuntu:12.04
  binary: docker
  socket: tcp://192.168.59.103:2376
  platform: ubuntu
  require_chef_omnibus: true

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[git::default]
    attributes:
